### ISSUE TITLE
Stürzt einfach ab

### ISSUE THREAD

**Issue by R4Tobi** [ColinHDev/GaTDsen#66]
Also bei einem Unentschieden wo jede Ratte onehit ist stürzt das spiel einfach ab.

```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "healthbar" because "com.gatdsen.animation.Animator.enemies[com.gatdsen.simulation.action.EnemyUpdateHealthAction.getTeam()][com.gatdsen.simulation.action.EnemyUpdateHealthAction.getPos().x][com.gatdsen.simulation.action.EnemyUpdateHealthAction.getPos().y]" is null
        at com.gatdsen.animation.Animator$ActionConverters.lambda$convertEnemyUpdateHealthAction$4(Animator.java:231)
        at com.gatdsen.animation.action.ExecutorAction.runAction(ExecutorAction.java:18)
        at com.gatdsen.animation.action.Action.step(Action.java:46)
        at com.gatdsen.animation.Animator.render(Animator.java:579)
        at com.gatdsen.ui.menu.InGameScreen.render(InGameScreen.java:85)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.gatdsen.ui.GADS.render(GADS.java:125)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at com.gatdsen.DesktopLauncher.main(DesktopLauncher.java:108)
```

**Comment by ColinHDev** [comment]
Unentschieden, wo jede Ratte onehit ist?
Ich bin mir nicht ganz sicher, wie ich das reproduzieren kann.. :(

**Comment by R4Tobi** [comment]
wenn im prinzip mehrere katzen eine maus angreifen und so die katze onehitten, ich denke das problem ist das es dann pfeile gibt die über das leben der katze hinausgehen oder so

**Comment by ColinHDev** [comment]
Ahh, ist reproduziert und @ldamitz weiß Bescheid & schaut es sich an

**Comment by ldamitz** [comment]
Fehler ist gesichtet und verstanden, der fix ist auch einfach. Aber ich werde vor Donnerstag Abend nicht dazu kommen. Danke fürs reporten! :)

**Comment by ColinHDev** [comment]
Dann baue ich den null-check nachher ein.. ಠ⁠_⁠ಠ

**Comment by ldamitz** [comment]
thx

**Comment by ColinHDev** [comment]
Sollte nun in [v1.0.2](https://vccourses.cs.ovgu.de/course/gatdsen/-/jobs/16533/artifacts/file/gaTDsen-1.0.2.jar) behoben sein.
Dankeschön für's Melden! :)

**Comment by ColinHDev** [comment]
Link sollte mittlerweile auch tatsächlich gehen. Da gab es wohl ein Problem mit der Sichtbarkeit... ._.
